// Content provenance for generated media.
//
// WHAT THIS IS, STATED PLAINLY
//
// This writes a provenance record into generated images, using the C2PA
// assertion vocabulary: what made the file, which model, when, and the
// digital source type that marks it as AI-generated. It is embedded in a PNG
// text chunk, so it survives a copy and travels with the file, and it is
// readable by anything that can read PNG metadata.
//
// It is NOT a cryptographically signed C2PA manifest. A signed manifest needs
// an X.509 certificate from a C2PA-recognized authority, and OpenShore has no
// such certificate. Calling an unsigned record a signed one would be exactly
// the overclaim this project refuses to make, so: this record is
// tamper-EVIDENT only in the weak sense that altering the pixels leaves the
// recorded hash mismatched, and anyone can rewrite the chunk. `signer` below is
// the seam a real C2PA signer slots into the day there is a certificate to
// sign with; until then `signature` is null and the record says so in its own
// text.
//
// The other half of the obligation is negative: provenance that arrives on an
// input is never stripped. hasProvenance lets a caller check before it writes.

export const PROVENANCE_KEYWORD = 'c2pa.manifest';
export const GENERATOR = 'OpenShore OS Code';

export interface ProvenanceAssertion {
  label: string;
  data: Record<string, unknown>;
}

export interface ProvenanceManifest {
  /** The claim generator, as C2PA names it. */
  claim_generator: string;
  /** The format of the asset this manifest describes. */
  format: string;
  /** ISO 8601 creation time. */
  created: string;
  assertions: ProvenanceAssertion[];
  /**
   * Null until a signing certificate exists. Present and null on purpose: a
   * reader can tell the difference between "unsigned" and "field missing".
   */
  signature: string | null;
  /** Plain language, embedded in the file itself, about what this record is. */
  note: string;
}

export const UNSIGNED_NOTE =
  'Self-attested provenance using the C2PA assertion vocabulary. Not a signed C2PA manifest: no signing certificate is present, so this record is not cryptographically verifiable.';

export interface ProvenanceInput {
  /** The model or image server that produced the asset. */
  model: string;
  /** Local or cloud, so the record says where the work happened. */
  modelPath: 'local' | 'cloud';
  format?: string;
  createdAt?: Date;
  /**
   * Tier 2 output allowed by an authorization assertion. The subject and the
   * fact of the assertion ride in the manifest, which is the accountability
   * half of the consent gate.
   */
  likenessSubject?: string;
  /** A signer, when one is ever configured. Absent means unsigned, stated. */
  signer?: (manifest: ProvenanceManifest) => string | null;
}

/** Build the manifest for a generated asset. */
export function buildProvenanceManifest(input: ProvenanceInput): ProvenanceManifest {
  const assertions: ProvenanceAssertion[] = [
    {
      label: 'c2pa.actions',
      data: {
        actions: [
          {
            action: 'c2pa.created',
            // The C2PA and IPTC term for content generated by a model.
            digitalSourceType:
              'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia',
            softwareAgent: GENERATOR,
            when: (input.createdAt ?? new Date()).toISOString(),
          },
        ],
      },
    },
    {
      label: 'com.openshore.generator',
      data: {
        model: input.model,
        modelPath: input.modelPath,
      },
    },
  ];
  if (input.likenessSubject) {
    assertions.push({
      label: 'com.openshore.likeness-authorization',
      data: {
        subject: input.likenessSubject,
        assertedBy: 'account holder',
        note: 'The account holder asserted authorization for this subject. An assertion is an accountability record, not verified proof of authorization.',
      },
    });
  }
  const manifest: ProvenanceManifest = {
    claim_generator: GENERATOR,
    format: input.format ?? 'image/png',
    created: (input.createdAt ?? new Date()).toISOString(),
    assertions,
    signature: null,
    note: UNSIGNED_NOTE,
  };
  const signature = input.signer?.(manifest) ?? null;
  return { ...manifest, signature };
}

// ---------------------------------------------------------------------------
// PNG chunk plumbing
// ---------------------------------------------------------------------------

const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

let crcTable: Uint32Array | undefined;

function crc32(bytes: Uint8Array): number {
  if (!crcTable) {
    crcTable = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      crcTable[n] = c >>> 0;
    }
  }
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) {
    crc = crcTable[(crc ^ bytes[i]!) & 0xff]! ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function isPng(bytes: Uint8Array): boolean {
  if (bytes.length < 8) return false;
  return PNG_SIGNATURE.every((b, i) => bytes[i] === b);
}

function latin1Bytes(text: string): Uint8Array {
  const out = new Uint8Array(text.length);
  for (let i = 0; i < text.length; i++) out[i] = text.charCodeAt(i) & 0xff;
  return out;
}

function utf8(text: string): Uint8Array {
  return new TextEncoder().encode(text);
}

/** Walk the chunks of a PNG. Returns [{type, start, dataStart, dataLength}]. */
function chunks(bytes: Uint8Array): Array<{ type: string; start: number; end: number }> {
  const out: Array<{ type: string; start: number; end: number }> = [];
  let offset = 8;
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  while (offset + 8 <= bytes.length) {
    const length = view.getUint32(offset, false);
    const type = String.fromCharCode(
      bytes[offset + 4]!,
      bytes[offset + 5]!,
      bytes[offset + 6]!,
      bytes[offset + 7]!,
    );
    const end = offset + 12 + length;
    if (end > bytes.length) break;
    out.push({ type, start: offset, end });
    if (type === 'IEND') break;
    offset = end;
  }
  return out;
}

/** Build an iTXt chunk carrying UTF-8 JSON under our keyword. */
function itxtChunk(keyword: string, text: string): Uint8Array {
  const key = latin1Bytes(keyword);
  const body = utf8(text);
  // keyword \0 compressionFlag compressionMethod languageTag \0 translatedKeyword \0 text
  const dataLength = key.length + 1 + 1 + 1 + 0 + 1 + 0 + 1 + body.length;
  const chunk = new Uint8Array(12 + dataLength);
  const view = new DataView(chunk.buffer);
  view.setUint32(0, dataLength, false);
  chunk.set(latin1Bytes('iTXt'), 4);
  let p = 8;
  chunk.set(key, p);
  p += key.length;
  chunk[p++] = 0; // null after keyword
  chunk[p++] = 0; // compression flag: uncompressed
  chunk[p++] = 0; // compression method
  chunk[p++] = 0; // empty language tag, null terminated
  chunk[p++] = 0; // empty translated keyword, null terminated
  chunk.set(body, p);
  const crc = crc32(chunk.subarray(4, 8 + dataLength));
  view.setUint32(8 + dataLength, crc, false);
  return chunk;
}

/**
 * Does this asset already carry provenance? Checked before writing, so an
 * input that arrives with a manifest is never quietly overwritten, and never
 * stripped.
 */
export function hasProvenance(bytes: Uint8Array): boolean {
  if (!isPng(bytes)) return false;
  for (const chunk of chunks(bytes)) {
    // A caBX chunk is a real C2PA (JUMBF) manifest. Its presence is provenance,
    // whatever it contains.
    if (chunk.type === 'caBX') return true;
    if (chunk.type !== 'iTXt' && chunk.type !== 'tEXt') continue;
    // Match on the chunk KEYWORD, never on its value. An earlier version grepped
    // the first ~192 bytes for "c2pa"/"xmp", which a prompt echoed into a tEXt
    // chunk (A1111, ComfyUI) could contain, silently suppressing labeling. The
    // keyword is the only thing that identifies a provenance chunk.
    const keyword = chunkKeyword(bytes, chunk);
    if (keyword === PROVENANCE_KEYWORD || keyword === 'XML:com.adobe.xmp') return true;
  }
  return false;
}

/**
 * The keyword of a tEXt or iTXt chunk: the latin1 bytes up to the first null.
 * PNG caps a keyword at 79 bytes, so the scan is bounded; an unterminated or
 * over-long field returns undefined rather than reading the whole chunk (which,
 * spread into String.fromCharCode, could throw on a crafted multi-megabyte
 * chunk).
 */
function chunkKeyword(bytes: Uint8Array, chunk: { start: number; end: number }): string | undefined {
  const dataStart = chunk.start + 8;
  const dataEnd = chunk.end - 4;
  const limit = Math.min(dataEnd, dataStart + 80);
  let p = dataStart;
  while (p < limit && bytes[p] !== 0) p++;
  if (p >= limit || bytes[p] !== 0) return undefined;
  let out = '';
  for (let i = dataStart; i < p; i++) out += String.fromCharCode(bytes[i]!);
  return out;
}

/**
 * Write the manifest into a PNG, immediately before IEND, leaving every other
 * chunk byte-identical. Returns the original bytes unchanged when the asset is
 * not a PNG (nothing is silently corrupted) or already carries provenance
 * (nothing is silently replaced).
 */
export function embedPngProvenance(
  bytes: Uint8Array,
  manifest: ProvenanceManifest,
): { bytes: Uint8Array; embedded: boolean; reason: string } {
  if (!isPng(bytes)) {
    return {
      bytes,
      embedded: false,
      reason: 'not a PNG, so no provenance chunk was written and nothing was altered',
    };
  }
  if (hasProvenance(bytes)) {
    return {
      bytes,
      embedded: false,
      reason: 'the asset already carries provenance, which is left exactly as it is',
    };
  }
  const iend = chunks(bytes).find((c) => c.type === 'IEND');
  if (!iend) {
    return { bytes, embedded: false, reason: 'malformed PNG: no IEND chunk' };
  }
  const chunk = itxtChunk(PROVENANCE_KEYWORD, JSON.stringify(manifest));
  const out = new Uint8Array(bytes.length + chunk.length);
  out.set(bytes.subarray(0, iend.start), 0);
  out.set(chunk, iend.start);
  out.set(bytes.subarray(iend.start), iend.start + chunk.length);
  return { bytes: out, embedded: true, reason: 'provenance written as an iTXt chunk before IEND' };
}

/** Read our manifest back out, for tests and for a reader that wants it. */
export function readPngProvenance(bytes: Uint8Array): ProvenanceManifest | undefined {
  if (!isPng(bytes)) return undefined;
  for (const chunk of chunks(bytes)) {
    if (chunk.type !== 'iTXt') continue;
    // Match on the keyword, read with a bounded scan (see chunkKeyword) so a
    // crafted unterminated field cannot throw here.
    if (chunkKeyword(bytes, chunk) !== PROVENANCE_KEYWORD) continue;
    const data = bytes.subarray(chunk.start + 8, chunk.end - 4);
    // keyword \0 flag method lang \0 translated \0 text
    let p = 0;
    while (p < data.length && data[p] !== 0) p++;
    p += 3; // null, compression flag, compression method
    while (p < data.length && data[p] !== 0) p++; // language tag
    p += 1;
    while (p < data.length && data[p] !== 0) p++; // translated keyword
    p += 1;
    try {
      return JSON.parse(new TextDecoder().decode(data.subarray(p))) as ProvenanceManifest;
    } catch {
      return undefined;
    }
  }
  return undefined;
}

/** Convenience: build and embed in one call. */
export function labelGeneratedImage(
  bytes: Uint8Array,
  input: ProvenanceInput,
): { bytes: Uint8Array; embedded: boolean; reason: string; manifest: ProvenanceManifest } {
  const manifest = buildProvenanceManifest(input);
  const result = embedPngProvenance(bytes, manifest);
  return { ...result, manifest };
}
