// Harbor Lite's fact cards: every part of the app a person can see, what it
// does, why it exists, and how to use it, one small card each. The guide
// harness (guideHarness.ts) hands the model only the few cards a question
// needs, so this list can be as complete as the app is without costing the
// window. Every card was checked against the screen that renders it
// (2026-09-24); when a screen changes, change its card in the same commit. The
// eval (guideEval.ts, test/guideEval.test.ts) pins which card answers which
// question. No em dashes, no backend internals. A current's name comes from its
// roster (currents.ts, harnessCurrents.ts), never spelled here.
import type { GuideCard } from './guideHarness.js';
import { guideStepsCompact } from './setupGuides.js';
import { AGENTIC_CURRENTS, AGENTIC_CURRENTS_TITLE } from './currents.js';
import { HARNESS_CURRENTS, HARNESS_CURRENTS_TITLE } from './harnessCurrents.js';

function listOf(names: readonly string[]): string {
  return names.length > 1
    ? `${names.slice(0, -1).join(', ')}, and ${names.at(-1)}`
    : (names[0] ?? '');
}

const agenticNames = AGENTIC_CURRENTS.map((c) => c.label);
const harnessNames = HARNESS_CURRENTS.map((c) => c.label);

export const GUIDE_CARDS: readonly GuideCard[] = [
  // ---------------------------------------------------------- the big picture
  {
    id: 'overview',
    title: 'What OpenShore is',
    text: 'OpenShore is a local-first coding assistant for your computer (Mac, Windows, or Linux) and your iPhone. You build a stack of models you own; local models are the default and the cloud is an opt-in choice on your own key. Once set up it works like a coding agent: say the goal, it proposes a plan, you pick, it does the work and asks before anything risky.',
    keywords: [
      'what is openshore',
      'how does openshore work',
      'overview',
      'purpose',
      'local-first',
      'coding assistant',
      'platforms',
      'windows',
      'linux',
    ],
  },
  {
    id: 'three-models',
    title: 'The three built-in models',
    text: 'Three models come out of the box. Harbor Lite is the tiny guide built into the iPhone app. Harbor is a coding model that runs on the iPhone. DeepBlue is the most capable, a real coding agent on your own computer. Paired, the phone reaches DeepBlue as My computer.',
    keywords: ['built-in models', 'three models', 'difference', 'compare', 'out of the box'],
  },
  {
    id: 'setup-page',
    title: 'Set up OpenShore',
    where: "The Set up OpenShore button under Harbor Lite's first message",
    text: 'The page for every optional next step. On the phone: Get Harbor, Connect your computer, Set up a repository, Connect your own API key. On your computer: Set up your local stack, Open a repository, Connect your own API key. In a new person\'s first chat Harbor Lite walks these steps with buttons under each message, and after Harbor it asks whether to start chatting or keep setting up, so setup never stands in the way; tap Pick up setup or say "let\'s set up" to pick it back up. There is no Get started group in Settings.',
    keywords: [
      'set up',
      'setup',
      'get started',
      'set up openshore',
      'onboarding',
      'next steps',
      'skipped',
      'first steps',
      'pick up setup',
    ],
  },
  {
    id: 'walk-me-through',
    title: 'Walk me through it',
    text: "Screens that set something up carry a Walk me through it (or Guide me) button that opens a chat with a step-by-step guide: the goal, a numbered plan, then one step at a time, with questions welcome between steps. It is on Cloud Connections, Desktop + phone on the phone, Repositories before you connect, Terminal, Crew command, Launch with Codemagic, and each current's connect sheet.",
    keywords: [
      'walk me through',
      'guide me',
      'tutorial',
      'step by step',
      'walkthrough',
      'instructions',
      'help me set up',
    ],
  },
  {
    id: 'menu',
    title: 'The Menu',
    where: 'Phone: the Menu button at top left, or swipe from the edge. Computer: the sidebar',
    text: 'Top: Chats, Projects, Terminal, Repositories, Stack, Vault. Bottom: Admin (company admins), My Crew, Marketplace (Coming soon), Stack Health, Launch with Codemagic, Cloud Connections, Desktop + phone, Settings. A Sign in row shows when you are signed out.',
    keywords: ['menu', 'sidebar', 'navigation', 'drawer', 'where is', 'find', 'rooms', 'hamburger'],
  },

  // ---------------------------------------------------------- the three models
  {
    id: 'harbor-lite',
    title: 'Harbor Lite',
    where: 'Built into the iPhone app; its row is in Menu, Settings, Harbor, marked Built in',
    text: 'Harbor Lite is the tiny guide (about 105 MB) that ships inside the iPhone app: here from first launch, offline, no account, and it cannot be removed. It explains the app, helps with setup, works out the best setup for your equipment, and looks simple questions up on the web when you are online. It does not write real code or run commands; for that it hands off to Harbor or DeepBlue.',
    keywords: [
      'harbor lite',
      'guide',
      'built in',
      'good for',
      'can you do',
      'what can you',
      'your limits',
      'who are you',
      'show me around',
    ],
  },
  {
    id: 'harbor',
    title: 'Harbor',
    where:
      'Menu, Settings, Harbor, Harbor on the phone, or Get Harbor on the Set up OpenShore page',
    text: `Harbor is a coding model (Qwen 2.5 Coder 3B, about 1.9 GB) that runs fully on the iPhone, private and even in airplane mode. It writes and explains code in chat and can search the web; it does not edit files or run commands yet. How to get it:\n${guideStepsCompact('get-harbor')}`,
    keywords: [
      'harbor',
      'get harbor',
      'phone coder',
      'coding model',
      'download harbor',
      'install harbor',
      'code on my phone',
      'switch to harbor',
    ],
  },
  {
    id: 'deepblue',
    title: 'DeepBlue',
    where:
      'OpenShore on your computer: Menu, Settings, Harbor, DeepBlue, or the first-run card, or Stack, Get DeepBlue',
    text: `DeepBlue is the most capable built-in model: a real coding agent that plans and edits your repositories on your own computer, running through Ollama and sized to your computer (Qwen 2.5 Coder 32B, 14B, 7B, or 3B). Once installed it is your Reasoning LLM, and a paired phone reaches it as My computer. How:\n${guideStepsCompact('get-harbor-master')}`,
    keywords: [
      'deepblue',
      'deep blue',
      'desktop model',
      'computer model',
      'coding agent',
      'ollama',
      'install on computer',
      'biggest model',
      'most capable',
    ],
  },

  // ---------------------------------------------------------- chat
  {
    id: 'chat-home',
    title: 'Chat',
    text: 'The main screen. The header shows the chat title (tap to rename), the repositories pill, spend so far, a context bar, and the connection pill. Type in the chat box and tap send.',
    keywords: ['chat', 'home', 'new chat', 'rename chat', 'context bar', 'main screen'],
  },
  {
    id: 'composer',
    title: 'The chat box',
    text: 'At the bottom of every chat: + to attach, the model pill, the mode pill, a Terminal pill on computer chats, the voice mode button, the dictation mic, and send. While a reply runs you can type to queue the next message, or tap the square to stop. Shift+Tab cycles the mode.',
    keywords: ['chat box', 'composer', 'send', 'stop', 'queue', 'buttons', 'keyboard shortcuts'],
  },
  {
    id: 'model-picker',
    title: 'Select model',
    where: 'Tap the model pill in the chat box, next to the +',
    text: 'Picks who answers: Stack, your pinned favorites, My computer (or Connect your computer), Cloud models, and Local models, plus Effort. Swipe a model left or tap its star to pin it. This is where you switch to Harbor once it is downloaded.',
    keywords: [
      'switch model',
      'switch',
      'different model',
      'pick model',
      'change model',
      'select model',
      'model pill',
      'my stack',
      'favorite',
      'pin',
      'local llms',
      'cloud providers',
    ],
  },
  {
    id: 'effort',
    title: 'Effort',
    where: 'Select model, Effort',
    text: 'Sets how hard the model thinks before answering: High (the default), Medium, or Low. Lower is faster.',
    keywords: ['effort', 'thinking', 'reasoning effort', 'faster', 'speed', 'thorough'],
  },
  {
    id: 'modes',
    title: 'Modes',
    where: 'The mode pill in the chat box, or Shift+Tab',
    text: 'Sets what the coding agent may do without asking. Ask first asks before every edit and command. Accept edits (the starting mode) lets file edits through but asks for commands. Plan is read-only and proposes a plan first. Bypass runs everything without asking, though cloud spend still asks. Plain chat models have no tools, so the mode does nothing there.',
    keywords: [
      'mode',
      'modes',
      'accept edits',
      'plan mode',
      'bypass',
      'default mode',
      'permission',
      'permissions',
      'auto approve',
    ],
  },
  {
    id: 'plan-first',
    title: 'Plan first',
    text: 'In Plan mode the agent writes its plan and stops. Tap Start building to go ahead, or Change something to adjust it with the plan still in view. It may also ask clarifying questions with tappable options. Nothing changes in your code until you approve.',
    keywords: ['plan first', 'start building', 'change something', 'approve plan', 'proposal'],
  },
  {
    id: 'approvals',
    title: 'Approvals',
    text: 'When the agent wants to edit, run a command, or spend on a cloud model, a sheet asks first, with a diff when there is one: Approve once, Always allow this in the project, Approve for this session, or No, skip it. Spend always asks.',
    keywords: ['approve', 'approval', 'allow', 'deny', 'confirm', 'asks first', 'diff', 'spend'],
  },
  {
    id: 'attachments',
    title: 'Attach',
    where: 'The + at the left of the chat box',
    text: 'Opens Camera, Photos, and Files (drag and drop on a computer). Videos are read as frames. Images only send if the chosen model can read images; if not, place an image-reading model in Stack or connect a cloud model that can.',
    keywords: [
      'attach',
      'photo',
      'image',
      'screenshot',
      'camera',
      'file',
      'video',
      'upload',
      'picture',
    ],
  },
  {
    id: 'dictation',
    title: 'Dictate',
    where: 'The mic icon in the chat box',
    text: 'Turns your speech into text in the chat box without sending it. Tap again to stop, then send.',
    keywords: ['mic', 'microphone', 'dictate', 'dictation', 'speech to text', 'voice typing'],
  },
  {
    id: 'voice-mode',
    title: 'Voice mode',
    where: 'The wave icon beside the mic; voice choices in Menu, Settings, Voice',
    text: 'A full-screen spoken conversation: it listens, sends what you said, and speaks the reply. Tap to interrupt or send. Approvals, spending, and pick lists come back to the screen, and everything lands in the chat as text. Settings, Voice picks the voice, speaking speed, and whether replies are read aloud.',
    keywords: [
      'voice',
      'voice mode',
      'talk',
      'speak',
      'hands free',
      'read aloud',
      'spoken',
      'speaking speed',
    ],
  },
  {
    id: 'slash-commands',
    title: 'Slash commands',
    text: 'Type / in the chat box: /help, /clear, /model, /cost, /mode, and /rename; agent chats add /compact (fold history to save room) and /init (write an OSCODE.md for the repository).',
    keywords: ['slash', 'commands', 'shortcut', 'compact', 'cost', 'init'],
  },
  {
    id: 'reach-pill',
    title: 'The connection pill',
    where: 'Top right of the chat',
    text: 'Shows your reach. Docked (green): your own computer is reachable, so everything works. Offshore (amber): online, but your computer is out of reach, so cloud and on-device models work. Offline (gray): on-device models only. Tap it to follow the connection automatically or step down by hand.',
    keywords: [
      'offshore',
      'docked',
      'pill',
      'top right',
      'connection',
      'status',
      'amber',
      'green',
      'reach',
    ],
  },
  {
    id: 'chats',
    title: 'Chats',
    where: 'Menu, Chats',
    text: 'Every chat, newest first, with search. Tap to open, swipe to delete, hold to rename. Sessions running on your paired computer show here too, so you can pick them up from the phone.',
    keywords: [
      'chats',
      'history',
      'old chats',
      'search chats',
      'delete chat',
      'past conversations',
      'resume',
    ],
  },

  // ---------------------------------------------------------- the stack
  {
    id: 'stack',
    title: 'Stack',
    where: 'Menu, Stack',
    text: 'The models that answer for you. One is the Reasoning LLM: it plans each task and sends it to the specialist whose job fits, or does it itself. You can keep a separate stack for each connection status (Docked, Offshore, Offline); the one for your current status is used automatically. It exists so you can mix models you own, each doing what it does best.',
    keywords: [
      'stack',
      'your stack',
      'reasoning llm',
      'orchestrator',
      'runs the show',
      'routing',
      'which model answers',
      'status stack',
    ],
  },
  {
    id: 'specialists',
    title: 'Specialists',
    where: 'Menu, Stack, Specialists',
    text: 'Models placed by job under the Reasoning LLM: Coding, Writing, Analysis, Image reading, Image creation, Retrieval, Fast, or Custom. Image reading has an on-device slot and a cloud slot. Add one from the Bench with Add to stack and pick its category.',
    keywords: [
      'specialist',
      'specialists',
      'coding',
      'writing',
      'analysis',
      'vision',
      'image reading',
      'retrieval',
      'category',
      'roles',
    ],
  },
  {
    id: 'bench',
    title: 'The Bench',
    where: 'Menu, Stack, Bench',
    text: 'Models you download or connect wait on the Bench until you place them. Teal is local and private, amber is cloud. Tap Add to stack, choose a category, and optionally a trigger, a persona, and effort.',
    keywords: [
      'bench',
      'place',
      'placement',
      'add to stack',
      'unplaced',
      'where did my model go',
      'teal',
    ],
  },
  {
    id: 'byom',
    title: 'Bring your own model',
    where: 'Menu, Stack, the BYOM + pill',
    text: 'Connects any OpenAI-compatible endpoint you control, like your own server or a fine-tune: a name, an address ending in /v1, a model id, and an optional API key. It lands on your Bench, and calls go straight from your device to it.',
    keywords: [
      'byom',
      'bring your own model',
      'own server',
      'self hosted',
      'custom endpoint',
      'openai compatible',
      'fine tune',
      'lm studio',
    ],
  },
  {
    id: 'stack-desktop',
    title: 'Stack on your computer',
    where: 'Menu, Stack, in OpenShore on your computer',
    text: 'Shows the Reasoning LLM with a Change button and the specialist roles, chosen from models installed through Ollama. Start with a prefab stack fills it in one tap and shows the size and any graphics memory it needs; with no models, the picker offers Get DeepBlue.',
    keywords: [
      'desktop stack',
      'computer stack',
      'prefab stack',
      'ollama models',
      'installed models',
      'enable specialist',
    ],
  },
  {
    id: 'first-seat',
    title: 'First Seat',
    text: 'On an empty chat when nothing can answer yet, one card sets you up: on your computer, one tap installs DeepBlue sized to it. More ways to start offers Connect your computer, Connect an API key, and Open Stack.',
    keywords: ['first run', 'no model', 'first seat', 'nothing answers', 'one tap', 'empty chat'],
  },
  {
    id: 'marketplace',
    title: 'Marketplace',
    where: 'Menu, Marketplace (grayed, Coming soon)',
    text: 'A catalog of more models rated against your hardware, downloaded straight from their source. It is marked Coming soon in the Menu; today you grow the stack with the three built-in models, a cloud model on your own API key, or your own model (BYOM), all from Stack and Settings, Harbor.',
    keywords: [
      'marketplace',
      'more models',
      'other models',
      'download models',
      'new model',
      'catalog',
      'store',
      'coming soon',
      'bundles',
    ],
  },
  {
    id: 'stack-health',
    title: 'Stack Health',
    where: 'Menu, Stack Health',
    text: 'An honest read of how your stack is used, worked out on your own computer, by day, week, or month: how much ran locally versus in the cloud, what the cloud cost, energy and carbon estimates, and leaner swaps.',
    keywords: [
      'stack health',
      'usage',
      'stats',
      'how much spent',
      'local vs cloud',
      'carbon',
      'energy',
      'dashboard',
    ],
  },

  // ---------------------------------------------------------- connections
  {
    id: 'cloud-connections',
    title: 'Cloud Connections',
    where: 'Menu, Cloud Connections',
    text: `Add cloud models on your own API key: Claude (which also needs its Workspace id), OpenAI, Gemini, Kimi (Moonshot), and Perplexity. Each connected provider puts its models on your Bench. API keys stay on your device, and nothing spends without your approval. How:\n${guideStepsCompact('connect-cloud-key')}`,
    keywords: [
      'cloud',
      'api key',
      'key',
      'claude',
      'anthropic',
      'openai',
      'gpt',
      'gemini',
      'kimi',
      'perplexity',
      'own key',
      'cloud connections',
      'paid model',
      'strongest',
    ],
  },
  {
    id: 'pair-phone',
    title: 'Connect your computer',
    where: 'Phone: Menu, Desktop + phone',
    text: `Connects the phone to OpenShore on your computer so the computer does the heavy lifting, your battery lasts, and a long answer keeps going when you close the app. It runs over your own private Tailscale network (free for personal use), so nothing is opened to the internet. How:\n${guideStepsCompact('pair-computer')}`,
    keywords: [
      'pair',
      'pairing',
      'connect my computer',
      'connect computer',
      'tailscale',
      'qr',
      'qr code',
      'my computer',
      'why tailscale',
      'private network',
      'hub',
    ],
  },
  {
    id: 'pair-desktop',
    title: 'Desktop + phone, on the computer',
    where: 'On your computer: Menu, Desktop + phone',
    text: 'Tap Turn on to open the phone connection over Tailscale; it shows a QR code and a one-time pairing code good for five minutes. Paired devices are listed and each can be revoked on its own.',
    keywords: ['turn on', 'show qr', 'pairing code', 'revoke', 'paired devices', 'desktop + phone'],
  },
  {
    id: 'repositories',
    title: 'Repositories',
    where: 'Menu, Repositories, and the repositories pill at the top of a chat',
    text: `Connect GitHub, GitLab, or Bitbucket (one tap, or an access token). With your computer connected you can clone from a URL or open a local folder. In a chat, the repositories pill picks which code that chat works on, with its branch. OpenShore reads, edits, tests, and commits with your approval on every change. How:\n${guideStepsCompact('open-a-repo')}`,
    keywords: [
      'repository',
      'repositories',
      'repo',
      'repos',
      'no repos',
      'github',
      'gitlab',
      'bitbucket',
      'git',
      'clone',
      'my code',
      'branch',
    ],
  },
  {
    id: 'terminal',
    title: 'Terminal',
    where: 'Menu, Terminal; the switch is in Menu, Settings, Terminal',
    text: 'A real terminal on your computer, following your coding session or in your home folder. Terminal Control off (the default) means you run commands; on means the model runs them and reads the output. In a computer chat, the Terminal pill runs your next message as a command.',
    keywords: [
      'terminal',
      'shell',
      'command line',
      'terminal control',
      'run command',
      'bash',
      'console',
    ],
  },
  {
    id: 'launch',
    title: 'Launch with Codemagic',
    where: 'Menu, Launch with Codemagic',
    text: `Ships your app to the App Store or Google Play through Codemagic on your own account: add a Codemagic API key and a launch target, then build. On a failed build the model can read the log. How:\n${guideStepsCompact('connect-codemagic')}`,
    keywords: [
      'launch',
      'codemagic',
      'app store',
      'google play',
      'ship',
      'testflight',
      'release',
      'deploy',
      'publish app',
    ],
  },

  // ---------------------------------------------------------- projects and knowledge
  {
    id: 'projects',
    title: 'Projects',
    where: 'Menu, Projects',
    text: 'A project keeps its chats, repositories, and standing instructions together, so the agent has the same context in every chat for it. Its room has New chat, Resume last chat, Standing instructions, Repositories and files, what the agent has learned there, and its currents.',
    keywords: ['project', 'projects', 'standing instructions', 'organize', 'folder', 'new project'],
  },
  {
    id: 'project-notes',
    title: 'What the agent has learned here',
    where: 'A project room, or Vault, Coding projects',
    text: 'Read-only notes the agent keeps in the project: Current State, Progress, Decisions, Action Items, and Skills, so the next session picks up where the last one left off.',
    keywords: [
      'learned',
      'project memory',
      'progress',
      'decisions',
      'action items',
      'current state',
    ],
  },
  {
    id: 'vault',
    title: 'Vault',
    where: 'Menu, Vault',
    text: 'A markdown knowledge base that works with Obsidian: plain .md files, [[wikilinks]], and linked mentions, written by you and your agent. Where it lives lets you keep it on this device, in a folder on your computer, in iCloud Drive, or in Google Drive, and Export writes it out as plain files. Routines leave their notes here.',
    keywords: [
      'vault',
      'notes',
      'note',
      'knowledge base',
      'obsidian',
      'markdown',
      'wikilinks',
      'second brain',
      'icloud',
      'google drive',
    ],
  },
  {
    id: 'my-crew',
    title: 'My Crew',
    where: 'Menu, My Crew',
    text: 'Your own roster of agents, each with a name, a persona, a rule for when it is called, and an activity level (Reviews the work, Joins on its own, or When you ask). Tap + New crew member to add one.',
    keywords: [
      'crew',
      'my crew',
      'agents',
      'reviewer',
      'persona',
      'team',
      'helpers',
      'custom agent',
    ],
  },
  {
    id: 'advisors',
    title: 'The advisor team',
    where: 'Menu, My Crew, Add the advisor team',
    text: 'One tap adds eight advisors: Technical Advisor (reviews the work), Marketing, Finance, and Creative Studio (join when a decision needs them), and Research, Coordinator, Sounding Board, and Strategy (answer when asked). They advise; you decide.',
    keywords: [
      'advisor',
      'advisors',
      'advisor team',
      'technical advisor',
      'marketing',
      'finance',
      'strategy',
      'sounding board',
    ],
  },
  {
    id: 'routines',
    title: 'Routines',
    where: 'Menu, My Crew, Crew command',
    text: 'A routine gives a crew member a task, a workspace, days, and a time. It runs on your own computer while your computer is on, and leaves a dated note in the Vault. Access is Read-only or May edit files, and commands still wait for your approval. There is a Morning review preset and Run now.',
    keywords: [
      'routine',
      'routines',
      'schedule',
      'every morning',
      'every day',
      'recurring',
      'automate',
      'crew command',
      'morning review',
      'while i sleep',
    ],
  },
  {
    id: 'agentic-currents',
    title: AGENTIC_CURRENTS_TITLE,
    where: 'Menu, Projects, a project (editors only)',
    text: `${AGENTIC_CURRENTS_TITLE} (beta) hand agent work in a project to an outside agent: ${listOf(agenticNames)}. They are off by default and one is on at a time per project. Turn one on and the rooms you already use gain rows for it; turn it off and every trace is gone. Connecting one is done once per device from its Set up link.`,
    keywords: [
      'agentic currents',
      'currents',
      'current',
      'other agents',
      'outside agent',
      'external agent',
      'beta',
      ...agenticNames.map((n) => n.toLowerCase()),
    ],
  },
  {
    id: 'harness-currents',
    title: HARNESS_CURRENTS_TITLE,
    where: 'Menu, Projects, a project (editors only)',
    text: `${HARNESS_CURRENTS_TITLE} (beta) layer a cheap decision method into how answers are made in a project. ${listOf(harnessNames)} picks which of your models answers a turn, skips steps that need no model, and checks results, each decision shown as an amber card. It only spends on a paid or cloud seat. One on at a time per project.`,
    keywords: [
      'harness currents',
      'decision',
      'save money',
      'cheaper',
      'cost saving',
      ...harnessNames.map((n) => n.toLowerCase()),
    ],
  },

  // ---------------------------------------------------------- settings
  {
    id: 'settings',
    title: 'Settings',
    where: 'Menu, Settings',
    text: 'Groups: Account, Privacy, Ethical boundaries, This device, Terminal, Launch with Codemagic, Stack Health, Harbor, Writing, Voice, Notifications (iPhone), Wayfinding, and Clear conversations. Set up steps are not here; they are on the Set up OpenShore page.',
    keywords: ['settings', 'preferences', 'options', 'configure', 'toggles'],
  },
  {
    id: 'settings-harbor',
    title: 'Harbor settings and web search',
    where: 'Menu, Settings, Harbor',
    text: 'Installs or removes the built-in models (Harbor on the phone, DeepBlue on your computer; Harbor Lite is Built in) and picks the web search provider: DuckDuckGo needs no API key, or add your own Brave Search or Tavily API key.',
    keywords: [
      'web search',
      'duckduckgo',
      'brave',
      'tavily',
      'search key',
      'search provider',
      'uninstall harbor',
    ],
  },
  {
    id: 'wayfinding',
    title: 'Wayfinding',
    where: 'Menu, Settings, Wayfinding',
    text: 'How the agent finds its way, on by default. Memory keeps what it has learned in your Vault and reads it back. Skills are reusable markdown recipes. Browser drives a browser on your paired computer and asks before every action. Research (off by default) runs web research through Perplexity once a Perplexity API key is connected.',
    keywords: [
      'wayfinding',
      'memory',
      'skills',
      'browser',
      'research',
      'deep research',
      'remember',
    ],
  },
  {
    id: 'humanize',
    title: 'Humanize Writing',
    where: 'Menu, Settings, Writing',
    text: 'On by default: keeps text a model writes for you plain and specific, free of chatbot tells. Turn it off in Settings, Writing.',
    keywords: [
      'humanize',
      'humanize writing',
      'sounds like ai',
      'writing style',
      'tone',
      'chatbot',
    ],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    where: 'Menu, Settings, Notifications (iPhone)',
    text: 'Downloads tells you when a model finishes downloading while you are away; Replies tells you when a reply is ready or a chat needs your approval. If they are off in iOS, turn them on in iOS Settings, OpenShore, Notifications.',
    keywords: ['notifications', 'notices', 'alerts', 'push', 'notify me'],
  },
  {
    id: 'this-device',
    title: 'This device',
    where: 'Menu, Settings, This device',
    text: 'Appearance (System, Light, Dark), an on-device activity log you can copy or clear, and Store tokens and secrets, an encrypted per-project note only a local model can use (off by default).',
    keywords: [
      'appearance',
      'dark mode',
      'light mode',
      'theme',
      'activity log',
      'store secrets',
      'tokens',
    ],
  },
  {
    id: 'account',
    title: 'Account',
    where: 'Menu, Settings, Account, or the Sign in row',
    text: 'Personal use needs no account. Signing in syncs your chats across devices. After creating one you choose personal or business; a business adds a company, admins, and a shared stack managed from Admin.',
    keywords: [
      'account',
      'sign in',
      'login',
      'sign up',
      'create account',
      'business',
      'company',
      'admin',
      'sync',
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy',
    where: 'Menu, Settings, Privacy and Ethical boundaries',
    text: 'Local models keep everything on your device. Cloud models run on your own API keys with your approval. Chats, projects, and API keys are encrypted on the device, and there is no telemetry. Only a cloud model you connect, or a web search, sends anything off the device.',
    keywords: [
      'privacy',
      'private',
      'keys',
      'secrets',
      'data',
      'telemetry',
      'tracking',
      'leave my phone',
      'safe',
      'secure',
      'encrypted',
    ],
  },
  {
    id: 'offline',
    title: 'Working offline',
    text: 'With no connection, on-device models (Harbor Lite, Harbor) still answer; your computer and cloud models wait for a connection, and a banner says so. Web search needs a connection.',
    keywords: [
      'offline',
      'no internet',
      'without internet',
      'airplane mode',
      'no signal',
      'no wifi',
    ],
  },
  {
    id: 'clear-conversations',
    title: 'Clear conversations',
    where: 'Menu, Settings, Clear conversations',
    text: 'Removes every chat from this device after you confirm. It cannot be undone; sessions on your computer stay there.',
    keywords: ['clear', 'delete all', 'wipe', 'reset', 'erase history'],
  },
];
