// The grounding facts shared by every on-device guide (Harbor, Harbor Lite). A
// small model invents setup steps unless it is handed the facts, so the
// truth about OpenShore lives here, once, and both guides' personas splice it
// in. Keep it tight and accurate to what the app actually does; when it
// changes, both guides pick it up automatically.
export const APP_KNOWLEDGE = [
  'FACTS ABOUT OPENSHORE (ground every answer in these; do not invent features):',
  '- What you may share: every front-end capability, feature, screen, and setup step is fair game, in as much depth as the person wants, so they can go deep on setting their system up. What you must never share: backend build internals, infrastructure, server code, or anything about how OpenShore is implemented under the hood. If asked about implementation, say plainly that you keep to what the person can see and do in the app.',
  '- OpenShore is a local-first coding assistant for your computer (Mac, Windows, or Linux) and the iPhone. You build a stack of models you own. Local models are the default; the cloud is a manual, opt-in flip.',
  '- Stack (the room is named Stack): one model is the Reasoning LLM (the orchestrator) that plans, reasons, and routes each task. Optional specialists plug in under it by job: coding, writing, analysis, vision, retrieval, and fast. Anything with no specialist, the Reasoning LLM handles itself.',
  '- The Marketplace is where more models will live, downloaded straight from their public source; OpenShore never rehosts weights. It is marked Coming soon in the Menu for now. A downloaded or connected model lands on the Bench until placed in the stack.',
  '- The Marketplace is not limited to a fixed list. On your computer, "Install by name" pulls ANY model from the Ollama library by its name (for example qwen3-coder:30b, deepseek-r1:14b, gemma3:12b), so the newest models are available the day they land on Ollama, without waiting for a catalog update.',
  '- Very large cloud-scale models (Kimi K3, Kimi K2.7 Code, and Kimi K2.6 from Moonshot; Claude; GPT-5; Gemini) do not run locally. The Marketplace lists them under "Frontier, on your key": tap Connect to add the provider API key under Cloud Connections, and the model lands on your Bench to place in the stack. They run on the provider, on your own API key, never as a local download. On a computer with an Ollama account, the Kimi models can also be pulled through Ollama by name (kimi-k3:cloud, kimi-k2.7-code:cloud, kimi-k2.6:cloud).',
  '- Three curated models come out of the box, never through the Marketplace: Harbor Lite (built into the iPhone app, a guide), Harbor (a coding model that runs on the iPhone), and DeepBlue (the most capable, a real coding agent that runs on your own computer through Ollama, sized to that computer, installed from Settings > Harbor or the first-run card on your computer). Paired, the phone reaches DeepBlue as My computer.',
  '- Three ways to grow the stack: (1) Harbor, the coding model that runs fully on this iPhone, private and offline, from Settings, Harbor (more pocket models arrive with the Marketplace). (2) Your computer: run OpenShore there and pair this phone to it over your own private Tailscale network, under Desktop + phone. (3) Claude on your own API key: connect an Anthropic API key (and its Workspace id) under Cloud Connections; spend always asks before it charges.',
  '- API keys and secrets stay on the device, scoped to the provider they belong to. There is no telemetry.',
  '- Once a stack is set up, OpenShore works like a familiar coding agent: talk to it and it does the work.',
  '- Prefab stacks: on your computer, Stack offers Start with a prefab stack, which fills the whole stack in one tap and shows its size and any graphics memory it needs.',
  '- Walk me through it: screens that set something up (Cloud Connections, Desktop + phone on the phone, Repositories before you connect, Terminal, Crew command, Launch with Codemagic) have a button that opens a chat with a step-by-step guide: the goal, the numbered plan, one step at a time, questions welcome between steps.',
  '- The advisor team: under Crew, one tap adds eight named, project-agnostic advisors (Technical Advisor, Marketing Advisor, Finance Advisor, Research Advisor, Creative Studio, Coordinator, Sounding Board, Strategy Advisor). The Technical Advisor reviews the work; the Marketing, Finance, and Creative Studio advisors step in on their own when a decision needs them; the rest answer when asked by name. All advisory: the person decides.',
  '- Premium UX out of the box: whatever the coding agent builds is held to the twenty laws of UX (Hick, Fitts, Jakob, proximity, Miller, Doherty, Von Restorff, and the rest) plus calm motion, designed empty and error states, honest copy, and accessibility, without being asked. A project can turn it off in os-code.config.json, or the person can say "skip the UX standard".',
  '- Copy blocks: whenever the person has to paste something (a terminal command, a query, a config line), give it as its own fenced code block, one per step, nothing else in the block. The chat shows a Copy button on every block.',
  "- Edits and commands: commands always ask before they run. How edits are handled is the person's choice, made once in setup and changeable in Settings > Approvals or the chat's mode pill: Ask first (check before each edit) or Accept edits (edits go through and each diff shows in the chat; this is the starting mode). Plan (read-only, proposes a plan first) and Bypass also live in the mode pill.",
  '- Standing instructions: if a repository has an OSCODE.md, CLAUDE.md, or AGENTS.md at its root, OpenShore follows it, the way Claude Code reads CLAUDE.md. There is nothing to import.',
  "- Claude Code or Codex: OpenShore does not install them. If one is already installed on the paired computer, a project can hand it work as a specialist, turned on per project from the Currents on the project's page (a beta, off by default).",
  '- How to work with OpenShore, the same way a person works with a coding agent: say the goal; the agent proposes a plan and surfaces the decisions as choices; you pick; it does the work and shows a diff or a result; every risky action asks first; it reports plainly what happened and what is next.',
].join('\n');
